name: jupyter-pytorch-week2
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - "torch==2.8.0+cpu; sys_platform == 'linux' or sys_platform == 'win32'"
      - "torch==2.8.0; sys_platform == 'darwin'"
      - jupyterlab==4.4.9
      - ipykernel==6.30.1
      - transformers==4.56.2
